FROM alpine:3.16

USER root

RUN apk update
RUN apk add jenkins
RUN apk add ansible
RUN apk add python3
CMD ["java", "-jar", "/usr/share/webapps/jenkins/jenkins.war", "--logfile=/var/log/jenkins/jenkins.log", "--httpPort=8080"]
EXPOSE 8080